apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hbixqm0kl-python
  janus-idp.io/tekton: hbixqm0kl-python
  backstage.io/kubernetes-id: hbixqm0kl-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hbixqm0kl-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
