apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hbixqm0kl-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hbixqm0kl-python 
  name: hbixqm0kl-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hbixqm0kl-python 
